version: '3.3'

services:
  db: # Container de SQL
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mydql
    restart: always
    env_file:
      - ./config/db.env
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8002:80
    restart: always
    env_file:
      - ./config/wp.env
    networks:
      - backend

volumes:
  db_data: {}

networks:
  backend:
    driver: bridge